global:
  environment: staging
  image:
    repository: asia-south1-docker.pkg.dev/bo-stage/bo-main/django-backend
    tag: latest

configMap:
  name: better-backend-app-config

streamer:
  appName: better-backend-app-streamer
  replicas: 1
  resources:
    requests:
      cpu: 2
      memory: 4Gi 
    limits:
      cpu: 3
      memory: 6Gi