name: Docker Build and Push

on:
  workflow_dispatch:
  # repository_dispatch:
  #   types: [trigger-docker-build]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Environment Variables
      - name: Set Environment Variables
        env:
          REGION: ${{ github.event.client_payload.region || 'asia-south1' }}
          PROJECT_ID: ${{ github.event.client_payload.project_id || 'bo-stage' }}
          REPO: ${{ github.event.client_payload.artifact_repo || 'bo-main' }}
          IMAGE: ${{ github.event.client_payload.image_name || 'django-backend' }}
          GITHUB_RUN_ID: ${{ github.event.client_payload.run_id }}
        run: |
          echo "REGION=${REGION}" >> $GITHUB_ENV
          echo "PROJECT_ID=${PROJECT_ID}" >> $GITHUB_ENV
          echo "REPO=${REPO}" >> $GITHUB_ENV
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo "TAG=$(date +%Y%m%d)-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      # Step 3: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 4: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev"

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}

      # Step 6: Output Docker Image URL
      - name: Output Docker Image URL
        run: 'echo "Docker Image URL: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}"'
